Repository ansible-middleware/amq_streams, pull requests merged in 2023-07, with the labels that each got.

#38 👥 Add new author and contributor
  galaxy.yml
  roles/amq_streams_broker/README.md
  roles/amq_streams_common/README.md
  roles/amq_streams_connect/README.md
  roles/amq_streams_zookeeper/README.md
Labels: documentation, minor_changes

#42 Enable Zookeeper authentication
  roles/amq_streams_broker/README.md
  roles/amq_streams_broker/defaults/main.yml
  roles/amq_streams_broker/tasks/main.yml
  roles/amq_streams_broker/templates/broker-jaas.conf.j2
  roles/amq_streams_zookeeper/README.md
  roles/amq_streams_zookeeper/defaults/main.yml
  roles/amq_streams_zookeeper/tasks/main.yml
  roles/amq_streams_zookeeper/templates/zookeeper-jaas.conf.j2
  roles/amq_streams_zookeeper/templates/zookeeper.properties.j2
Labels: major_changes

#61 Add a molecule scenario for all_auth
  molecule/all_auth/converge.yml
  molecule/all_auth/molecule.yml
  molecule/all_auth/prepare.yml
  molecule/all_auth/requirements.yml
  molecule/all_auth/roles
  molecule/all_auth/verify.yml
Labels: minor_changes

#67 💚 Update topic management in test playbooks
  playbooks/amq_streams_all_cluster.yml
  playbooks/amq_streams_distributed.yml
Labels: minor_changes
